import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/ui/HeaderComponent/HeaderComponent";
import FooterNavigation from "@/ui/FooterNavigation/FooterNavigation";
import GoogleMapsWrapper from "@/ui/GoogleMapsWrapper/GoogleMapsWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen w-full max-h-screen overflow-auto bg-green-700 flex flex-col px-2">
          <Header />
          <div className="w-full h-full content-height text-center pb-24">
            <GoogleMapsWrapper>
              {children}
            </GoogleMapsWrapper>
          </div>


          {/* Footer Navigation */}

        </div>
        <div className="flex justify-center mb-4 h-fit absolute z-50 bottom-0 left-1/2 right-1/2">
          <FooterNavigation />
        </div>
      </body>
    </html>
  );
}
